/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LotteryRouteImport } from './routes/lottery'
import { Route as IndexRouteImport } from './routes/index'

const LotteryRoute = LotteryRouteImport.update({
  id: '/lottery',
  path: '/lottery',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lottery': typeof LotteryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lottery': typeof LotteryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lottery': typeof LotteryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/lottery'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/lottery'
  id: '__root__' | '/' | '/lottery'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LotteryRoute: typeof LotteryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/lottery': {
      id: '/lottery'
      path: '/lottery'
      fullPath: '/lottery'
      preLoaderRoute: typeof LotteryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LotteryRoute: LotteryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
